services:
  mysql:
    build:
      context: .
      dockerfile: docker/Dockerfile.mysql
    container_name: movement_ranking_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: movement_ranking
      MYSQL_USER: api_user
      MYSQL_PASSWORD: api_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - movement_ranking_network
    command:
      - --default-authentication-plugin=mysql_native_password

  php:
    build:
      context: .
      dockerfile: docker/Dockerfile.php
    container_name: movement_ranking_php
    volumes:
      - ./src:/var/www
      - ./docker/logs/php:/var/log/php-fpm
    depends_on:
      - mysql
    networks:
      - movement_ranking_network
    environment:
      DB_HOST: mysql
      DB_NAME: movement_ranking
      DB_USER: api_user
      DB_PASSWORD: api_password
      DB_PORT: 3306
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003 discover_client_host=1 log_level=1"

  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    container_name: movement_ranking_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/logs/nginx:/var/log/nginx
    depends_on:
      - php
    networks:
      - movement_ranking_network

volumes:
  mysql_data:

networks:
  movement_ranking_network:
    driver: bridge

